apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
  labels:
    app: kubernetes-bootcamp
spec:
  ports:
  - port: 8080
  type: NodePort
  selector:
    app: kubernetes-bootcamp-script
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-bootcamp-script
  name: kubernetes-bootcamp-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-bootcamp-script
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp-script
    spec:
      containers:
      - image: gcr.io/google-samples/kubernetes-bootcamp:v1
        name: master
        ports:
        - containerPort: 8080